export const DB_NAME = 'DB';

export const DOCUMENT_YAHOO = 'YAHOO';
export const DOCUMENT_YAHOO_DAY = 'YAHOO_DAY';

export const DOCUMENT_SETUSOKU = 'DOCUMENT_SETUSOKU';
export const DOCUMENT_SETUSOKU_DAY = 'SETUSOKU_DAY';

export const DOCUMENT_NYUSOKU_DAY = 'DOCUMENT_NYUSOKU_DAY';
export const DOCUMENT_NYUSOKU_PLUS_DAY = 'DOCUMENT_NYUSOKU_PLUS_DAY';

// export const DOCUMENT_UROKO = 'DOCUMENT_UROKO';
// export const DOCUMENT_COCONALA_PROGRAMMING = 'PROGRAMMING';
// export const DOCUMENT_COCONALA_WEB = 'WEB';
